---
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
install: true
env:
- EXAMPLE_PATH=./todo-modern MODERN=1
- EXAMPLE_PATH=./TodoMVC
- EXAMPLE_PATH=./relay-treasurehunt
- EXAMPLE_PATH=./star-wars
- EXAMPLE_PATH=./todo
before_script:
  (cd $EXAMPLE_PATH && npm install)
script:
  (cd $EXAMPLE_PATH && npm run update-schema && { if [ -n "$MODERN" ]; then npm run build; fi })
